# Generated by Django 5.0.6 on 2024-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(help_text='Enter the Language the book is written in', max_length=200, unique=True)),
            ],
            options={
                'ordering': ['language_name'],
            },
        ),
    ]
