# Generated by Django 5.0.6 on 2024-07-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': (['due_back'],), 'permissions': (('can_mark_returned', 'Set book as imerudishwa'),)},
        ),
    ]
